import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const api = readFileSync(new URL("../lib/supabase-rest.ts", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const checks = [
  ["01 session type has access token", api.includes("access_token: string")],
  ["02 session type has refresh token", api.includes("refresh_token: string")],
  ["03 session type has expiry", api.includes("expires_in: number")],
  ["04 session contains user id", api.includes("user: { id: string")],
  ["05 session contains optional email", api.includes("email?: string")],
  ["06 refresh uses refresh grant", api.includes("grant_type=refresh_token")],
  ["07 refresh posts securely", api.includes("method: \"POST\"")],
  ["08 refresh sends token in body", api.includes("refresh_token: refreshToken")],
  ["09 signup endpoint exists", api.includes("/auth/v1/signup")],
  ["10 logout endpoint exists", api.includes("/auth/v1/logout")],
  ["11 logout uses authenticated headers", api.includes("headers(token)")],
  ["12 stores session refreshing state", page.includes("sessionRefreshing, setSessionRefreshing")],
  ["13 refreshing starts false", page.includes("useState(false);\n  const [sessionNotice")],
  ["14 stores session notice", page.includes("sessionNotice, setSessionNotice")],
  ["15 stores preview visibility", page.includes("profilePreviewOpen, setProfilePreviewOpen")],
  ["16 preview starts visible", page.includes("setProfilePreviewOpen] = useState(true)")],
  ["17 derives public initials", page.includes("const publicProfileInitials")],
  ["18 initials use display name", page.includes("myProfile.display_name || session?.user.email")],
  ["19 initials split words", page.includes(".split(/\\s+/)")],
  ["20 initials use two words maximum", page.includes(".slice(0, 2)")],
  ["21 initials are uppercase", page.includes("toUpperCase()")],
  ["22 centralizes local session clearing", page.includes("function clearLocalSession")],
  ["23 clearing removes saved session", page.includes('removeItem("coqui-session")')],
  ["24 clearing resets session", page.includes("setSession(null)")],
  ["25 clearing resets favorites", page.includes("setFavoriteIds(new Set())")],
  ["26 clearing exits favorite-only mode", page.includes("setFavoritesOnly(false)")],
  ["27 clearing closes account", page.includes("setAccountOpen(false)")],
  ["28 clearing preserves notice", page.includes("setSessionNotice(notice)")],
  ["29 manual renewal function exists", page.includes("async function renewCurrentSession")],
  ["30 renewal requires refresh token", page.includes("!session?.refresh_token")],
  ["31 renewal avoids duplicate request", page.includes("|| sessionRefreshing")],
  ["32 renewal starts progress", page.includes("setSessionRefreshing(true)")],
  ["33 renewal clears old notice", page.includes('setSessionNotice("")')],
  ["34 renewal calls refresh", page.includes("refreshSession(session.refresh_token)")],
  ["35 renewal updates live session", page.includes("setSession(renewed)")],
  ["36 renewal saves session", page.includes('setItem("coqui-session", JSON.stringify(renewed))')],
  ["37 renewal confirms success", page.includes("Sesión renovada correctamente")],
  ["38 renewal handles expiry", page.includes("Tu sesión venció. Inicia sesión nuevamente para continuar de forma segura")],
  ["39 renewal opens login", page.includes("setAuthOpen(true)")],
  ["40 renewal always ends progress", page.includes("setSessionRefreshing(false)")],
  ["41 startup reads saved session", page.includes('getItem("coqui-session")')],
  ["42 startup parses saved session", page.includes("JSON.parse(saved) as Session")],
  ["43 startup refreshes session", page.includes("refreshSession(stored.refresh_token)")],
  ["44 startup replaces renewed session", page.includes("setSession(renewed)")],
  ["45 startup handles expired session", page.includes("Tu sesión anterior venció")],
  ["46 automatic refresh schedules timer", page.includes("window.setTimeout")],
  ["47 automatic refresh occurs before expiry", page.includes("session.expires_in - 60")],
  ["48 refresh delay has safe minimum", page.includes("Math.max(30")],
  ["49 timer cleanup exists", page.includes("window.clearTimeout(timer)")],
  ["50 automatic expiry reopens login", page.includes("Inicia sesión nuevamente para continuar")],
  ["51 signin confirms secure session", page.includes("Sesión iniciada de forma segura")],
  ["52 logout calls server", page.includes("await signOut(session.access_token)")],
  ["53 logout always clears locally", page.includes("finally { clearLocalSession")],
  ["54 logout confirms completion", page.includes("Sesión cerrada correctamente")],
  ["55 profile keeps exact address private", page.includes("Tu dirección exacta")],
  ["56 profile keeps documents private", page.includes("documentos")],
  ["57 profile keeps private phone hidden", page.includes("teléfono privado")],
  ["58 profile keeps internal verification private", page.includes("información interna de verificación")],
  ["59 completion tracks three public fields", page.includes("de 3 datos públicos añadidos")],
  ["60 completion progress uses percentage", page.includes("profileCompletion / 3 * 100")],
  ["61 privacy summary is accessible", page.includes('aria-label="Resumen de privacidad del perfil"')],
  ["62 visible profile data explained", page.includes("Nombre, pueblo y presentación")],
  ["63 visible data is user-controlled", page.includes("Solo lo que decides escribir aquí")],
  ["64 private account data explained", page.includes("Correo, teléfono y dirección exacta")],
  ["65 private data is not public", page.includes("No aparecen en tu perfil público")],
  ["66 protected data explained", page.includes("Documentos y verificaciones internas")],
  ["67 admin separation explained", page.includes("Coquí Admin los maneja de forma separada")],
  ["68 public preview exists", page.includes('className="public-profile-preview"')],
  ["69 preview tells user its purpose", page.includes("Así te verá la comunidad")],
  ["70 preview can be hidden", page.includes("setProfilePreviewOpen((open) => !open)")],
  ["71 preview toggle is accessible", page.includes("aria-expanded={profilePreviewOpen}")],
  ["72 preview has fallback initials", page.includes('publicProfileInitials || "CV"')],
  ["73 preview has name fallback", page.includes("Tu nombre público")],
  ["74 preview has municipality fallback", page.includes("Pueblo no mostrado")],
  ["75 preview has bio fallback", page.includes("Tu presentación aparecerá aquí")],
  ["76 preview labels community profile", page.includes("Perfil de la comunidad")],
  ["77 public name stays required", page.includes("input required minLength={2} maxLength={80}")],
  ["78 public name has help relation", page.includes('aria-describedby="public-name-tip"')],
  ["79 public name help is concrete", page.includes("compradores y vendedores te reconozcan")],
  ["80 town remains controlled selector", page.includes("<select value={myProfile.municipality}")],
  ["81 town can remain hidden", page.includes('<option value="">No mostrar</option>')],
  ["82 bio remains length-limited", page.includes("textarea maxLength={500}")],
  ["83 bio shows character count", page.includes("myProfile.bio.length}/500")],
  ["84 profile warns against phone", page.includes("No incluyas teléfono")],
  ["85 profile warns against exact address", page.includes("dirección exacta ni datos bancarios")],
  ["86 profile warns against documents", page.includes("No publiques documentos")],
  ["87 profile warns against passwords", page.includes("contraseñas o códigos")],
  ["88 profile requests respectful presentation", page.includes("breve, respetuosa y útil")],
  ["89 session card is accessible", page.includes('aria-label="Seguridad de la sesión"')],
  ["90 session card labels private account", page.includes("Cuenta privada")],
  ["91 email is shown only to owner", page.includes("session.user.email")],
  ["92 email privacy is explained", page.includes("no se muestra en el perfil público")],
  ["93 protected connection is explained", page.includes("Conexión protegida")],
  ["94 auto-renewal is explained", page.includes("renueva tu sesión automáticamente")],
  ["95 manual renewal button exists", page.includes("Renovar sesión ahora")],
  ["96 renewal button exposes progress", page.includes("Renovando…")],
  ["97 device logout is explicit", page.includes("Cerrar sesión en este dispositivo")],
  ["98 session notice is live status", page.includes('className="session-notice" role="status"')],
  ["99 privacy summary adapts to mobile", css.includes(".profile-privacy-summary{grid-template-columns:1fr}")],
  ["100 session card adapts to mobile", css.includes(".session-card{grid-template-columns:1fr}")],
];

assert.equal(checks.length, 100);
for (const [name, condition] of checks) test(name, () => assert.equal(condition, true));
