import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const api = readFileSync(new URL("../lib/supabase-rest.ts", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const checks = [
  ["01 recovery API exists", api.includes("function requestPasswordReset")],
  ["02 recovery API accepts email", api.includes("requestPasswordReset(email: string")],
  ["03 recovery API accepts redirect", api.includes("redirectTo: string")],
  ["04 recovery uses auth endpoint", api.includes("/auth/v1/recover")],
  ["05 recovery redirect is encoded", api.includes("encodeURIComponent(redirectTo)")],
  ["06 recovery uses POST", api.includes('method: "POST"')],
  ["07 recovery sends JSON headers", api.includes("headers: headers()")],
  ["08 recovery sends email only", api.includes("body: JSON.stringify({ email })")],
  ["09 password update API exists", api.includes("function updatePassword")],
  ["10 password update accepts token", api.includes("updatePassword(token: string")],
  ["11 password update accepts password", api.includes("password: string")],
  ["12 password update uses user endpoint", api.includes("/auth/v1/user")],
  ["13 password update uses PUT", api.includes('method: "PUT"')],
  ["14 password update authenticates", api.includes("headers: headers(token)")],
  ["15 password update sends password", api.includes("JSON.stringify({ password })")],
  ["16 auth mode supports recovery", page.includes('"login" | "signup" | "recovery"')],
  ["17 auth password state exists", page.includes("authPassword, setAuthPassword")],
  ["18 password visibility state exists", page.includes("passwordVisible, setPasswordVisible")],
  ["19 new password state exists", page.includes("newPassword, setNewPassword")],
  ["20 confirmation state exists", page.includes("confirmNewPassword, setConfirmNewPassword")],
  ["21 changing state exists", page.includes("passwordChanging, setPasswordChanging")],
  ["22 export state exists", page.includes("dataExporting, setDataExporting")],
  ["23 signup checks minimum length", page.includes("length: authPassword.length >= 8")],
  ["24 signup checks uppercase", page.includes("upper: /[A-Z]/.test(authPassword)")],
  ["25 signup checks lowercase", page.includes("lower: /[a-z]/.test(authPassword)")],
  ["26 signup checks number", page.includes("number: /\\d/.test(authPassword)")],
  ["27 signup checks symbol", page.includes("symbol: /[^A-Za-z0-9]/.test(authPassword)")],
  ["28 password score uses checks", page.includes("Object.values(passwordChecks).filter(Boolean).length")],
  ["29 new password requires ten", page.includes("newPassword.length >= 10")],
  ["30 new password requires uppercase", page.includes("/[A-Z]/.test(newPassword)")],
  ["31 new password requires lowercase", page.includes("/[a-z]/.test(newPassword)")],
  ["32 new password requires number", page.includes("/\\d/.test(newPassword)")],
  ["33 new password requires symbol", page.includes("/[^A-Za-z0-9]/.test(newPassword)")],
  ["34 email is trimmed", page.includes('.trim().toLowerCase()')],
  ["35 email is normalized lowercase", page.includes("toLowerCase()")],
  ["36 recovery branch exists", page.includes('authMode === "recovery"')],
  ["37 recovery uses current origin", page.includes("window.location.origin")],
  ["38 recovery avoids account enumeration", page.includes("Si existe una cuenta con ese correo")],
  ["39 recovery promises secure link", page.includes("enlace seguro para recuperar el acceso")],
  ["40 weak signup is blocked", page.includes("passwordScore < 4")],
  ["41 weak password guidance exists", page.includes("Usa una contraseña más fuerte")],
  ["42 password change handler exists", page.includes("function handlePasswordChange")],
  ["43 handler prevents default", page.includes("event.preventDefault()")],
  ["44 handler requires session", page.includes("!session || passwordChanging")],
  ["45 handler clears old notice", page.includes('setSessionNotice("")')],
  ["46 handler validates strength", page.includes("!newPasswordValid")],
  ["47 handler explains requirements", page.includes("10 caracteres, mayúscula, minúscula, número y símbolo")],
  ["48 handler compares confirmation", page.includes("newPassword !== confirmNewPassword")],
  ["49 mismatch message exists", page.includes("Las contraseñas nuevas no coinciden")],
  ["50 changing begins before request", page.includes("setPasswordChanging(true)")],
  ["51 update uses current token", page.includes("updatePassword(session.access_token, newPassword)")],
  ["52 new password is cleared", page.includes('setNewPassword("")')],
  ["53 confirmation is cleared", page.includes('setConfirmNewPassword("")')],
  ["54 update success message exists", page.includes("Contraseña actualizada")],
  ["55 update failure is handled", page.includes("No pudimos actualizar la contraseña")],
  ["56 changing always stops", page.includes("setPasswordChanging(false)")],
  ["57 export function exists", page.includes("function exportMyAccountData")],
  ["58 export requires session", page.includes("!session || dataExporting")],
  ["59 export marks progress", page.includes("setDataExporting(true)")],
  ["60 export records date", page.includes("exported_at: new Date().toISOString()")],
  ["61 export includes account id", page.includes("id: session.user.id")],
  ["62 export includes owner email", page.includes("email: session.user.email || null")],
  ["63 export includes public profile", page.includes("public_profile: myProfile")],
  ["64 export includes listings", page.includes("listings: myListings")],
  ["65 export includes offers", page.includes("offers: myOffers")],
  ["66 export summarizes conversations", page.includes("message_count: messages.length")],
  ["67 export includes confirmations", page.includes("sale_confirmations: saleConfirmations")],
  ["68 export includes transactions", page.includes("transactions: myTransactions")],
  ["69 export includes reviews", page.includes("reviews: myReviews")],
  ["70 export includes reports", page.includes("reports: myReports")],
  ["71 export includes disputes", page.includes("disputes: myDisputes")],
  ["72 export includes preferences", page.includes("notification_preferences: notificationPreferences")],
  ["73 export serializes readable JSON", page.includes("JSON.stringify(exportPayload, null, 2)")],
  ["74 export uses JSON MIME", page.includes('type: "application/json"')],
  ["75 export creates object URL", page.includes("URL.createObjectURL(blob)")],
  ["76 export creates local link", page.includes('document.createElement("a")')],
  ["77 export filename identifies product", page.includes("coqui-ventas-mis-datos-")],
  ["78 export filename includes date", page.includes("toISOString().slice(0, 10)")],
  ["79 export starts download", page.includes("link.click()")],
  ["80 export revokes URL", page.includes("URL.revokeObjectURL(downloadUrl)")],
  ["81 export confirms privacy", page.includes("Tu copia privada fue preparada")],
  ["82 export always ends progress", page.includes("setDataExporting(false)")],
  ["83 recovery heading exists", page.includes("Recupera tu acceso")],
  ["84 recovery explains email link", page.includes("Te enviaremos un enlace seguro")],
  ["85 password hidden in recovery", page.includes('authMode !== "recovery"')],
  ["86 password toggle exists", page.includes("setPasswordVisible((visible) => !visible)")],
  ["87 toggle has show label", page.includes("Mostrar contraseña")],
  ["88 toggle has hide label", page.includes("Ocultar contraseña")],
  ["89 signup meter is live", page.includes('className="password-strength" aria-live="polite"')],
  ["90 meter computes percentage", page.includes("passwordScore / 5 * 100")],
  ["91 meter labels weak", page.includes('"Débil"')],
  ["92 meter labels very strong", page.includes('"Muy fuerte"')],
  ["93 forgot password entry exists", page.includes("Olvidé mi contraseña")],
  ["94 recovery submit is explicit", page.includes("Enviar enlace seguro")],
  ["95 recovery returns to login", page.includes("Volver a iniciar sesión")],
  ["96 security tools are labelled", page.includes('aria-label="Herramientas de seguridad de la cuenta"')],
  ["97 password rule pills exist", css.includes(".new-password-rules span")],
  ["98 completed rules are distinct", css.includes(".new-password-rules span.met")],
  ["99 security form adapts mobile", css.includes(".account-security-tools form{grid-template-columns:1fr}" )],
  ["100 export button adapts mobile", css.includes(".account-data-export button{width:100%}")],
];

assert.equal(checks.length, 100);
for (const [name, condition] of checks) test(name, () => assert.equal(condition, true));
