import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const api = readFileSync(new URL("../lib/supabase-rest.ts", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const checks = [
  ["01 private profile query includes status", api.includes("bio,account_status,phone_verified")],
  ["02 private profile query includes phone verification", api.includes("phone_verified")],
  ["03 private profile query includes identity verification", api.includes("identity_verified")],
  ["04 private profile query includes creation date", api.includes("identity_verified,created_at")],
  ["05 profile query remains owner scoped", api.includes("&id=eq.${userId}&limit=1")],
  ["06 profile query uses authenticated headers", api.includes("headers: headers(token)")],
  ["07 account status state exists", page.includes("accountStatus, setAccountStatus")],
  ["08 active status is supported", page.includes('"active" | "restricted"')],
  ["09 restricted status is supported", page.includes('"restricted" | "suspended"')],
  ["10 suspended status is supported", page.includes('"suspended" | "deleted"')],
  ["11 deleted status is supported", page.includes('"deleted">("active")')],
  ["12 status defaults active", page.includes('useState<"active" | "restricted" | "suspended" | "deleted">("active")')],
  ["13 phone verification state exists", page.includes("phoneVerified, setPhoneVerified")],
  ["14 identity verification state exists", page.includes("identityVerified, setIdentityVerified")],
  ["15 device clearing state exists", page.includes("deviceDataCleared, setDeviceDataCleared")],
  ["16 active is only writable state", page.includes('accountStatus === "active"')],
  ["17 account status details exist", page.includes("const accountStatusDetails")],
  ["18 active label is friendly", page.includes('active: { label: "Activa"')],
  ["19 active detail allows buying", page.includes("Puedes comprar, publicar")],
  ["20 active detail allows messaging", page.includes("comunicarte normalmente")],
  ["21 restricted label is friendly", page.includes('restricted: { label: "Restringida"')],
  ["22 restricted keeps history", page.includes("consultar tu historial")],
  ["23 restricted limits new actions", page.includes("acciones nuevas están limitadas")],
  ["24 suspended label is friendly", page.includes('suspended: { label: "Suspendida"')],
  ["25 suspended keeps history", page.includes("Tu historial se conserva")],
  ["26 suspended blocks new actions", page.includes("no puedes realizar acciones nuevas")],
  ["27 deleted label avoids harsh wording", page.includes('deleted: { label: "Cerrada"')],
  ["28 deleted explains protected history", page.includes("historial protegido se conserva")],
  ["29 write guard exists", page.includes("function guardAccountWrite")],
  ["30 write guard has account destination", page.includes('"account" | "session"')],
  ["31 write guard permits active", page.includes("if (accountCanWrite) return true")],
  ["32 write guard uses current label", page.includes("accountStatusDetails.label.toLowerCase()")],
  ["33 write guard uses current detail", page.includes("accountStatusDetails.detail")],
  ["34 account guard reports in account", page.includes("setAccountMessage(message)")],
  ["35 session guard reports in session", page.includes("setSessionNotice(message)")],
  ["36 blocked guard returns false", page.includes("return false")],
  ["37 device clearing function exists", page.includes("function clearPrivateDeviceData")],
  ["38 clears recent searches", page.includes('removeItem("coqui-recent-searches")')],
  ["39 clears recently viewed storage", page.includes('removeItem("coqui-recently-viewed")')],
  ["40 clears recently viewed state", page.includes("setRecentlyViewedIds([])")],
  ["41 clears comparisons", page.includes("setCompareIds([])")],
  ["42 closes comparison modal", page.includes("setComparisonOpen(false)")],
  ["43 clears current search", page.includes('setSearchTerm("")')],
  ["44 records local clearing", page.includes("setDeviceDataCleared(true)")],
  ["45 confirms local clearing", page.includes("Borramos las búsquedas")],
  ["46 confirmation mentions recent views", page.includes("vistas recientes")],
  ["47 confirmation mentions comparisons", page.includes("comparaciones guardadas")],
  ["48 profile load assigns active fallback", page.includes('? profile.account_status : "active"')],
  ["49 profile load recognizes restricted", page.includes('profile?.account_status === "restricted"')],
  ["50 profile load recognizes suspended", page.includes('profile?.account_status === "suspended"')],
  ["51 profile load recognizes deleted", page.includes('profile?.account_status === "deleted"')],
  ["52 phone status comes from server", page.includes("setPhoneVerified(Boolean(profile?.phone_verified))")],
  ["53 identity status comes from server", page.includes("setIdentityVerified(Boolean(profile?.identity_verified))")],
  ["54 profile save invokes guard", page.includes("!session || !guardAccountWrite()")],
  ["55 publishing invokes guard", page.includes('!guardAccountWrite("session")')],
  ["56 blocked publishing opens account", page.includes("setAccountOpen(true)")],
  ["57 blocked publishing opens profile tab", page.includes('setAccountTab("profile")')],
  ["58 status center is rendered", page.includes('className={`account-status-center status-${accountStatus}`}')],
  ["59 status center is accessible", page.includes('aria-label="Estado y verificaciones de la cuenta"')],
  ["60 status heading exists", page.includes("Estado de la cuenta")],
  ["61 current status label renders", page.includes("accountStatusDetails.label")],
  ["62 current status detail renders", page.includes("accountStatusDetails.detail")],
  ["63 active status uses check icon", page.includes('accountStatus === "active" ? "✓"')],
  ["64 restricted status uses warning icon", page.includes('accountStatus === "restricted" ? "!"')],
  ["65 suspended status uses pause icon", page.includes('accountStatus === "suspended" ? "⏸"')],
  ["66 closed status uses close icon", page.includes(': "×"}</i>')],
  ["67 readonly note is conditional", page.includes("!accountCanWrite &&")],
  ["68 readonly note announces status", page.includes('className="account-readonly-note" role="status"')],
  ["69 readonly keeps information", page.includes("Tu información e historial permanecen disponibles")],
  ["70 readonly blocks publications", page.includes("bloquea publicaciones")],
  ["71 readonly blocks changes", page.includes("cambios y mensajes nuevos")],
  ["72 verification area is accessible", page.includes('aria-label="Verificaciones administradas por Coquí Ventas"')],
  ["73 phone verification is shown", page.includes("phoneVerified ? \"verified\" : \"pending\"")],
  ["74 phone verified copy exists", page.includes('phoneVerified ? "Verificado"')],
  ["75 phone unverified copy exists", page.includes(': "No verificado"')],
  ["76 identity verification is shown", page.includes("identityVerified ? \"verified\" : \"pending\"")],
  ["77 identity verified copy exists", page.includes('identityVerified ? "Verificada"')],
  ["78 identity unverified copy exists", page.includes(': "No verificada"')],
  ["79 verification purpose is explained", page.includes("ayudan a proteger la comunidad")],
  ["80 self approval is prohibited in copy", page.includes("no puede aprobarlas")],
  ["81 self status change is prohibited", page.includes("cambiar el estado de su propia cuenta")],
  ["82 admin authority is explicit", page.includes("solo Coquí Admin puede hacerlo")],
  ["83 admin review is required", page.includes("después de una revisión")],
  ["84 device privacy control renders", page.includes('className="device-privacy-control"')],
  ["85 device control names scope", page.includes("Privacidad de este dispositivo")],
  ["86 device control explains searches", page.includes("Elimina búsquedas recientes")],
  ["87 device control explains viewed items", page.includes("publicaciones vistas")],
  ["88 device control explains comparisons", page.includes("lista de comparación")],
  ["89 device control does not delete account", page.includes("No borra tu cuenta")],
  ["90 device control preserves listings", page.includes("publicaciones, mensajes ni transacciones")],
  ["91 device clear button exists", page.includes("Borrar actividad del dispositivo")],
  ["92 device clear completion label exists", page.includes("Datos locales borrados")],
  ["93 profile submit blocks readonly", page.includes("busy || !accountCanWrite")],
  ["94 readonly submit label exists", page.includes("Cuenta en modo consulta")],
  ["95 status center has base style", css.includes(".account-status-center{")],
  ["96 restricted has distinct style", css.includes(".account-status-center.status-restricted")],
  ["97 suspended has distinct style", css.includes(".account-status-center.status-suspended")],
  ["98 closed has distinct style", css.includes(".account-status-center.status-deleted")],
  ["99 verification grid adapts mobile", css.includes(".verification-statuses{grid-template-columns:1fr}")],
  ["100 privacy control adapts mobile", css.includes(".device-privacy-control button{width:100%}")],
];

assert.equal(checks.length, 100);
for (const [name, condition] of checks) test(name, () => assert.equal(condition, true));
