import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const checks = [
  ["stores conversation search", page.includes('const [conversationSearch, setConversationSearch]')],
  ["starts conversation search empty", page.includes('setConversationSearch] = useState("")')],
  ["stores conversation filter", page.includes('const [conversationFilter, setConversationFilter]')],
  ["supports all conversations", page.includes('"all" | "offers" | "pending" | "messages"')],
  ["starts conversation filter at all", page.includes('setConversationFilter] = useState<"all" | "offers" | "pending" | "messages">("all")')],
  ["counts offers per conversation", page.includes("const conversationOfferCount")],
  ["relates offers to listing", page.includes("offer.listing_id === conversation.listing_id")],
  ["counts pending offers per conversation", page.includes("const conversationPendingOfferCount")],
  ["pending counter checks status", page.includes('offer.status === "pending"')],
  ["creates filtered conversations", page.includes("const filteredConversations = [...myConversations].filter")],
  ["searches person", page.includes("conversation.other_person")],
  ["searches listing title", page.includes("conversation.listing_title")],
  ["searches message bodies", page.includes('conversation.messages.map((message) => message.body).join(" ")')],
  ["normalizes searchable conversation", page.includes("normalizeSearch(searchable)")],
  ["normalizes conversation query", page.includes("normalizeSearch(conversationSearch)")],
  ["matches all filter", page.includes('conversationFilter === "all"')],
  ["matches conversations with offers", page.includes('conversationFilter === "offers" ? offers > 0')],
  ["matches pending conversations", page.includes('conversationFilter === "pending" ? pendingOffers > 0')],
  ["matches conversations with messages", page.includes("conversation.messages.length > 0")],
  ["combines conversation filters", page.includes("matchesSearch && matchesFilter")],
  ["sorts filtered conversations", page.includes("}).sort((first, second) =>")],
  ["uses latest first message date", page.includes("first.messages.at(-1)?.created_at")],
  ["falls back to conversation date", page.includes("first.created_at")],
  ["sorts descending", page.includes("new Date(secondDate).getTime() - new Date(firstDate).getTime()")],
  ["builds conversation counts", page.includes("const conversationCounts =")],
  ["counts all conversations", page.includes("all: myConversations.length")],
  ["counts conversations with offers", page.includes("conversationOfferCount(conversation) > 0")],
  ["counts conversations needing response", page.includes("conversationPendingOfferCount(conversation) > 0")],
  ["counts conversations with messages", page.includes("conversation.messages.length > 0")],
  ["detects active conversation filters", page.includes("const conversationFiltersActive = Boolean")],
  ["provides clear conversation filters", page.includes("function clearConversationFilters()")],
  ["clears conversation search", page.includes('setConversationSearch("")')],
  ["clears conversation filter", page.includes('setConversationFilter("all")')],
  ["renders messages center", page.includes('className="messages-center"')],
  ["labels conversation summary", page.includes('aria-label="Resumen de conversaciones"')],
  ["shows all summary", page.includes("['all','Todas']")],
  ["shows offers summary", page.includes("['offers','Con ofertas']")],
  ["shows pending summary", page.includes("['pending','Esperan respuesta']")],
  ["shows messages summary", page.includes("['messages','Con mensajes']")],
  ["summary buttons filter", page.includes("setConversationFilter(filter)")],
  ["summary buttons report pressed", page.includes("aria-pressed={conversationFilter === filter}")],
  ["renders conversation toolbar", page.includes('className="conversation-toolbar"')],
  ["renders search input", page.includes('value={conversationSearch}')],
  ["search has useful placeholder", page.includes('placeholder="Persona, publicación o mensaje"')],
  ["search is accessible", page.includes('aria-label="Buscar conversaciones por persona, publicación o mensaje"')],
  ["updates conversation search", page.includes("setConversationSearch(event.target.value)")],
  ["shows clear filters conditionally", page.includes("conversationFiltersActive &&")],
  ["announces filtered count", page.includes('filteredConversations.length} conversación')],
  ["renders filtered list", page.includes("filteredConversations.map")],
  ["counts each thread offers", page.includes("const offerCount = conversationOfferCount")],
  ["counts pending thread offers", page.includes("const pendingOfferCount = conversationPendingOfferCount")],
  ["shows pending badge", page.includes('pendiente{pendingOfferCount === 1 ? "" : "s"}')],
  ["shows message count", page.includes('conversation.messages.length} mensaje')],
  ["shows offer count", page.includes('offerCount > 0 ? ` · ${offerCount} oferta')],
  ["shows recent date", page.includes('toLocaleDateString("es-PR", {day:"numeric",month:"short"})')],
  ["shows filtered empty state", page.includes("No encontramos conversaciones")],
  ["offers show-all recovery", page.includes("Prueba otra búsqueda o muestra todos tus chats")],
  ["styles conversation summary", css.includes(".conversation-summary{display:grid")],
  ["styles pending badge", css.includes(".conversation-list>button i")],
  ["adapts conversation center on mobile", css.includes(".conversation-summary{grid-template-columns:repeat(2,1fr)}")],
];

assert.equal(checks.length, 60);
for (const [name, condition] of checks) test(name, () => assert.equal(condition, true));
