import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const api = readFileSync(new URL("../lib/supabase-rest.ts", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const expectations = [
  [page, 'className="listing-seller-line"'],
  [page, "event.stopPropagation()"],
  [page, "if (listing.seller_id)"],
  [page, "setPublicSellerId(listing.seller_id)"],
  [page, "Ver perfil público de"],
  [page, "listing.seller_avatar_url ?"],
  [page, "src={listing.seller_avatar_url}"],
  [page, 'alt=""'],
  [page, "width={56}"],
  [page, "height={56}"],
  [page, "unoptimized"],
  [page, 'listing.seller_display_name || "CV"'],
  [page, ".slice(0, 1).toUpperCase()"],
  [page, 'listing.seller_display_name || "Miembro de Coquí Ventas"'],
  [page, "listing-seller-rating"],
  [page, 'className="listing-seller-rating verified"'],
  [page, "reseñas verificadas"],
  [page, "listing.seller_rating ?"],
  [page, "listing.seller_rating.toFixed(1)"],
  [page, "de 5 estrellas"],
  [page, "listing.seller_review_count"],
  [page, "reseñas"],
  [page, "transacciones verificables"],
  [page, "verificadas"],
  [page, "Vendedor nuevo sin reseñas"],
  [page, 'title="Reseñas de transacciones verificables"'],
  [page, "Reseñas de transacciones verificables"],
  [page, "★"],
  [page, "· {listing.seller_review_count}"],
  [page, "listing.seller_review_count === 1"],
  [page, '"" : "s"'],
  [page, "☆ Nuevo · sin reseñas"],
  [page, "☆ Nuevo · sin reseñas"],
  [page, ">Ver perfil</i>"],
  [page, "publicSellerRating"],
  [page, "publicSellerReviewCount"],
  [page, 'className="public-seller-reputation verified"'],
  [page, 'aria-label="Resumen de reputación"'],
  [page, "public-seller-stars"],
  [page, "Reputación visible"],
  [page, 'publicSellerRating ? "★★★★★" : "☆☆☆☆☆"'],
  [page, "Solo mostramos información relacionada"],
  [page, "de transacciones verificables"],
  [page, "seller-public-rating"],
  [page, "selectedListing.seller_rating"],
  [page, "selectedListing.seller_review_count"],
  [page, "reseña{selectedListing.seller_review_count === 1"],
  [page, "Reputación verificable"],
  [page, "reseñas posteriores a transacciones verificables"],
  [page, "Ver perfil público y sus anuncios"],
  [api, "seller_rating:"],
  [api, "seller_review_count:"],
  [api, "sellerRatings ? sellerRatings.total / sellerRatings.count : null"],
  [api, "ratingBySeller"],
  [api, "profileBySeller"],
  [api, "seller_display_name:"],
  [api, "seller_avatar_url:"],
  [api, "review_count"],
  [api, "sellerRatings.total / sellerRatings.count"],
  [api, "reviews"],
  [api, "seller_id"],
  [api, "profileBySeller.get(row.seller_id)"],
  [api, "ratingBySeller.get(row.seller_id)"],
  [api, '"Miembro de Coquí Ventas"'],
  [api, "sellerProfile?.avatar_url || null"],
  [css, ".listing-seller-line{display:flex"],
  [css, "align-items:center"],
  [css, "gap:7px"],
  [css, "border-top:1px solid var(--line)"],
  [css, ".listing-seller-line>span{width:28px"],
  [css, "height:28px"],
  [css, "border-radius:50%"],
  [css, ".listing-seller-line img,.seller-avatar img"],
  [css, "object-fit:cover"],
  [css, ".listing-seller-line>b{max-width:30%"],
  [css, "flex:0 1 auto"],
  [css, ".listing-seller-rating{flex:0 0 auto"],
  [css, "padding:4px 6px"],
  [css, "border-radius:999px"],
  [css, "background:#e9f6f3"],
  [css, "color:#075f5b"],
  [css, "font-size:7px"],
  [css, "font-weight:900"],
  [css, "white-space:nowrap"],
  [css, ".listing-seller-rating.demo"],
  [css, "border:1px solid #ead58d"],
  [css, "background:#fff8dc"],
  [css, "color:#725b08"],
  [css, ".listing-seller-rating.verified"],
  [css, "border:1px solid #a9d7ce"],
  [css, ".listing-seller-line>i{flex:0 0 auto}"],
  [css, ".listing-seller-line:focus-visible"],
  [css, "outline:3px solid #57bcb2"],
  [css, "outline-offset:3px"],
  [css, "@media(max-width:560px)"],
  [css, "align-items:flex-start"],
  [css, "flex-wrap:wrap"],
  [css, "max-width:calc(100% - 92px)"],
  [css, ".listing-seller-rating{order:4"],
  [css, "margin-left:35px"],
];

assert.equal(expectations.length, 100);
for (const [index, [source, snippet]] of expectations.entries()) {
  test(`${String(index + 1).padStart(3, "0")} ${snippet}`, () => assert.equal(source.includes(snippet), true));
}
