import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const checks = [
  ["stores offer search", page.includes('const [offerSearch, setOfferSearch]')],
  ["starts offer search empty", page.includes('useState("");\n  const [offerStatusFilter')],
  ["stores offer status filter", page.includes('const [offerStatusFilter, setOfferStatusFilter]')],
  ["supports all offer status", page.includes('"all" | "pending" | "accepted" | "closed"')],
  ["starts with all statuses", page.includes('setOfferStatusFilter] = useState<"all" | "pending" | "accepted" | "closed">("all")')],
  ["stores offer direction", page.includes('const [offerDirectionFilter, setOfferDirectionFilter]')],
  ["supports received direction", page.includes('"received" | "sent"')],
  ["starts with all directions", page.includes('setOfferDirectionFilter] = useState<"all" | "received" | "sent">("all")')],
  ["calculates offer counts", page.includes("const offerCounts = myOffers.reduce")],
  ["counts all offers", page.includes("counts.all += 1")],
  ["counts pending offers", page.includes('offer.status === "pending"')],
  ["counts accepted offers", page.includes('else if (offer.status === "accepted") counts.accepted += 1')],
  ["counts closed offers", page.includes("else counts.closed += 1")],
  ["initializes all count", page.includes("{ all: 0, pending: 0, accepted: 0, closed: 0 }")],
  ["creates filtered offers", page.includes("const filteredMyOffers = myOffers.filter")],
  ["detects received offers", page.includes("offer.offered_by_user_id !== session.user.id")],
  ["normalizes offer title", page.includes('normalizeSearch(offer.listings?.title || "Publicación")')],
  ["normalizes offer query", page.includes("normalizeSearch(offerSearch)")],
  ["matches all direction", page.includes('offerDirectionFilter === "all"')],
  ["matches received direction", page.includes('offerDirectionFilter === "received" ? received : !received')],
  ["matches all status", page.includes('offerStatusFilter === "all"')],
  ["groups terminal statuses", page.includes('!["pending", "accepted"].includes(offer.status)')],
  ["matches direct status", page.includes("offer.status === offerStatusFilter")],
  ["combines offer filters", page.includes("matchesSearch && matchesDirection && matchesStatus")],
  ["detects active offer filters", page.includes("const offerFiltersActive = Boolean")],
  ["provides clear offer filters", page.includes("function clearOfferFilters()")],
  ["clears search", page.includes('setOfferSearch("")')],
  ["clears status", page.includes('setOfferStatusFilter("all")')],
  ["clears direction", page.includes('setOfferDirectionFilter("all")')],
  ["labels offer summary", page.includes('aria-label="Resumen de ofertas"')],
  ["shows all summary", page.includes("['all', 'Todas']")],
  ["shows pending summary", page.includes("['pending', 'Pendientes']")],
  ["shows accepted summary", page.includes("['accepted', 'Aceptadas']")],
  ["shows closed summary", page.includes("['closed', 'Finalizadas']")],
  ["summary filters on click", page.includes("onClick={() => setOfferStatusFilter(status)}")],
  ["summary reports pressed state", page.includes("aria-pressed={offerStatusFilter === status}")],
  ["renders offer toolbar", page.includes('className="offer-toolbar"')],
  ["uses search input", page.includes('input type="search" value={offerSearch}')],
  ["offers clear search hint", page.includes('placeholder="Buscar por publicación"')],
  ["labels search accessibly", page.includes('aria-label="Buscar ofertas por publicación"')],
  ["updates search", page.includes("setOfferSearch(event.target.value)")],
  ["renders direction selector", page.includes("value={offerDirectionFilter}")],
  ["labels direction accessibly", page.includes('aria-label="Filtrar ofertas por dirección"')],
  ["offers received option", page.includes('<option value="received">Recibidas</option>')],
  ["offers sent option", page.includes('<option value="sent">Enviadas</option>')],
  ["shows reset only when useful", page.includes("offerFiltersActive &&")],
  ["labels reset action", page.includes("Limpiar filtros")],
  ["announces result count", page.includes('className="offer-result-count" aria-live="polite"')],
  ["renders filtered offers", page.includes("filteredMyOffers.map")],
  ["preserves accept action", page.includes('changeOfferStatus(offer.id, "accepted")')],
  ["preserves counter action", page.includes("openCounterOffer(offer)")],
  ["preserves reject action", page.includes('changeOfferStatus(offer.id, "rejected")')],
  ["preserves withdraw action", page.includes('changeOfferStatus(offer.id, "withdrawn")')],
  ["shows filtered empty state", page.includes("No encontramos ofertas con esos filtros")],
  ["offers view-all recovery", page.includes("Ver todas las ofertas")],
  ["styles summary grid", css.includes(".offer-summary-grid{display:grid")],
  ["styles active summary", css.includes(".offer-summary-grid button.active")],
  ["styles toolbar", css.includes(".offer-toolbar{display:grid")],
  ["adapts summary on mobile", css.includes(".offer-summary-grid{grid-template-columns:repeat(2,1fr)}")],
  ["stacks offer actions on mobile", css.includes(".offer-actions{justify-content:stretch;flex-direction:column}")],
];

assert.equal(checks.length, 60);
for (const [name, condition] of checks) test(name, () => assert.equal(condition, true));
