import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const pageExpectations = [
  "publicSellerListings",
  "listing.seller_id === publicSellerId",
  ".sort((first, second)",
  "new Date(second.created_at || 0)",
  "new Date(first.created_at || 0)",
  "publicSellerLead",
  "publicSellerRating",
  "reduce((total, listing)",
  "Number(listing.seller_rating || 0)",
  "publicSellerReviewCount",
  "reduce((highest, listing)",
  "Math.max(highest",
  "Number(listing.seller_review_count || 0)",
  'className="public-seller-reputation verified"',
  'publicSellerRating ? "★★★★★" : "☆☆☆☆☆"',
  "publicSellerAvailableCount",
  '(listing.status || "available") === "available"',
  "publicSellerPendingCount",
  'listing.status === "pending"',
  "publicSellerSoldCount",
  'listing.status === "sold"',
  "publicSellerTowns",
  "new Set(publicSellerListings",
  "setPublicSellerId(null)",
  'event.key === "Escape"',
  "seller-profile-backdrop",
  "event.target === event.currentTarget",
  "public-seller-modal",
  'role="dialog"',
  'aria-modal="true"',
  'aria-labelledby="public-seller-title"',
  'aria-describedby="public-seller-description"',
  'aria-label="Cerrar perfil público"',
  "public-seller-avatar",
  "publicSellerLead.seller_avatar_url",
  'alt={`Foto de ${publicSellerLead.seller_display_name',
  "width={144}",
  "height={144}",
  "Perfil público",
  'id="public-seller-title"',
  'id="public-seller-description"',
  "Solo mostramos información relacionada",
  "public-seller-reputation",
  'aria-label="Resumen de reputación"',
  "public-seller-stars",
  "de 5 estrellas",
  "Vendedor nuevo sin reseñas",
  "Reputación visible",
  "publicSellerReviewCount === 1",
  "transacciones verificables",
  "de transacciones verificables",
  "Vendedor nuevo sin reseñas",
  "Solo mostramos información relacionada",
  "public-seller-stats",
  "Publicaciones visibles",
  "publicSellerTowns.length || 1",
  "Disponible",
  "public-seller-statuses",
  'aria-label="Estado de publicaciones"',
  "publicSellerPendingCount > 0",
  "publicSellerSoldCount > 0",
  "visibles por 24 h",
  "Publicaciones de este vendedor",
  "publicSellerListings.map",
  'aria-label={`Ver ${listing.title}',
  "openListing(listing)",
  "listing.image_urls[0]",
  "listingAge(listing.created_at)",
  "seller-listing-status",
  "Tu privacidad primero",
];

const cssExpectations = [
  ".public-seller-reputation{display:grid",
  "margin-top:16px",
  "padding:13px 14px",
  "border:1px solid #b8ddd5",
  "border-radius:13px",
  "linear-gradient(135deg,#edf9f6,#fff)",
  ".public-seller-reputation>div{display:flex",
  ".public-seller-stars{color:#e5a916",
  "letter-spacing:2px",
  ".public-seller-reputation b{color:var(--teal-dark)",
  ".public-seller-reputation p{margin:0",
  ".public-seller-reputation small{color:#7a6421",
  ".public-seller-reputation.demo{border-color:#ead58d",
  "background:#fffaf0",
  ".public-seller-statuses{display:flex",
  "flex-wrap:wrap",
  "margin:-7px 0 14px",
  ".public-seller-statuses span{padding:5px 8px",
  "border-radius:999px",
  ".public-seller-listings button em",
  ".seller-listing-status.pending",
  "background:#fff0bd",
  ".seller-listing-status.sold",
  "background:#edf1f2",
  ".public-seller-modal>footer b",
  ".public-seller-listings>button:focus-visible",
  "outline:3px solid #57bcb2",
  "outline-offset:2px",
  ".public-seller-listings>button:hover",
  "border-color:#8dc9c2",
];

const checks = [
  ...pageExpectations.map((snippet) => [snippet, page.includes(snippet)]),
  ...cssExpectations.map((snippet) => [snippet, css.includes(snippet)]),
];

assert.equal(checks.length, 100);
for (const [index, [name, condition]] of checks.entries()) {
  test(`${String(index + 1).padStart(3, "0")} ${name}`, () => assert.equal(condition, true));
}
