import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const api = readFileSync(new URL("../lib/supabase-rest.ts", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const checks = [
  ["001 listing carries seller id", api.includes("seller_id?: string")],
  ["002 listing carries seller name", api.includes("seller_display_name?: string")],
  ["003 listing carries avatar URL", api.includes("seller_avatar_url?: string | null")],
  ["004 profile carries avatar URL", api.includes("avatar_url?: string | null")],
  ["005 public listing query requests seller", api.includes("category_id,seller_id,title")],
  ["006 public query permits available", api.includes("status=in.(available,pending,sold)")],
  ["007 public query permits pending", api.includes("available,pending,sold")],
  ["008 public query limits results", api.includes("limit=100")],
  ["009 public query is uncached", api.includes('cache: "no-store"')],
  ["010 public query uses publishable headers", api.includes("headers()")],
  ["011 seller ids are deduplicated", api.includes("new Set")],
  ["012 seller ids come from listings", api.includes("row.seller_id")],
  ["013 blank seller ids are removed", api.includes("Boolean(id)")],
  ["014 profiles only load when needed", api.includes("sellerIds.length")],
  ["015 profile request includes id", api.includes("select=id,display_name,avatar_url")],
  ["016 profile request includes public name", api.includes("display_name")],
  ["017 profile request includes avatar", api.includes("avatar_url")],
  ["018 profile request filters seller ids", api.includes("&id=in.(")],
  ["019 profile request filters active status", api.includes("account_status=eq.active")],
  ["020 profile request avoids cache", api.includes('cache: "no-store"')],
  ["021 profile request tolerates failure", api.includes(".catch(() => [])")],
  ["022 seller profile map exists", api.includes("profileBySeller")],
  ["023 profile map keys by id", api.includes("[profile.id, profile]")],
  ["024 profile map keeps display name", api.includes("display_name: string")],
  ["025 profile map keeps avatar", api.includes("avatar_url: string | null")],
  ["026 listing resolves its seller profile", api.includes("profileBySeller.get(row.seller_id)")],
  ["027 listing resolves ratings separately", api.includes("ratingBySeller.get(row.seller_id)")],
  ["028 seller name joins listing", api.includes("seller_display_name: sellerProfile?.display_name")],
  ["029 seller avatar joins listing", api.includes("seller_avatar_url: sellerProfile?.avatar_url")],
  ["030 missing name has safe fallback", api.includes('"Miembro de Coquí Ventas"')],
  ["031 missing avatar becomes null", api.includes("sellerProfile?.avatar_url || null")],
  ["032 sold visibility remains 24 hours", api.includes("24 * 60 * 60 * 1000")],
  ["033 image loading remains independent", api.includes("downloadListingImage")],
  ["034 real images remain independent", api.includes("image_urls") && !api.includes("uses_demo_images")],
  ["035 seller ratings remain attached", api.includes("seller_rating:")],
  ["036 review counts remain attached", api.includes("seller_review_count:")],
  ["037 missing ratings remain transparent", api.includes("sellerRatings ? sellerRatings.total / sellerRatings.count : null")],
  ["038 profile detail requests avatar", api.includes("display_name,avatar_url,municipality")],
  ["039 profile detail requires active", api.includes("account_status=eq.active")],
  ["040 profile detail is owner-targeted", api.includes("id=eq.${sellerId}")],
  ["041 listing card seller row renders", page.includes('className="listing-seller-line"')],
  ["042 seller row follows municipality", page.includes('Puerto Rico</p>\n                    <button type="button" className="listing-seller-line"')],
  ["043 card checks avatar", page.includes("listing.seller_avatar_url ?")],
  ["044 card renders avatar with Image", page.includes("src={listing.seller_avatar_url}")],
  ["045 card seller button identifies seller", page.includes('aria-label={`Ver perfil público de ${listing.seller_display_name')],
  ["046 card avatar width is fixed", page.includes("width={56}")],
  ["047 card avatar height is fixed", page.includes("height={56}")],
  ["048 card avatar permits public URL", page.includes("height={56} unoptimized")],
  ["049 card falls back to seller initial", page.includes(".slice(0, 1).toUpperCase()")],
  ["050 card falls back to CV identity", page.includes('listing.seller_display_name || "CV"')],
  ["051 card prints seller name", page.includes('listing.seller_display_name || "Miembro de Coquí Ventas"')],
  ["052 card keeps transparency pills", page.includes('className="card-transparency"')],
  ["053 card keeps publication age", page.includes("listingAge(listing.created_at)")],
  ["054 card keeps favorite action", page.includes("toggleFavorite(listing.id)")],
  ["055 card keeps sharing action", page.includes("shareListing(listing)")],
  ["056 card keeps compare action", page.includes("toggleComparison(listing.id)")],
  ["057 card remains keyboard reachable", page.includes("tabIndex={0}")],
  ["058 card keeps button role", page.includes('role="button"')],
  ["059 card supports Enter", page.includes('event.key === "Enter"')],
  ["060 card supports Space", page.includes('event.key === " "')],
  ["061 detail seller card renders", page.includes('className="seller-public-card"')],
  ["062 detail checks authenticated profile avatar", page.includes("sellerProfile?.avatar_url")],
  ["063 detail falls back to listing avatar", page.includes("selectedListing.seller_avatar_url")],
  ["064 detail avatar uses Image", page.includes("width={104} height={104}")],
  ["065 detail avatar alt identifies seller", page.includes('alt={`Foto de ${sellerProfile?.display_name')],
  ["066 detail falls back to profile initial", page.includes("sellerProfile?.display_name?.slice(0, 1)")],
  ["067 detail falls back to listing initial", page.includes("selectedListing.seller_display_name?.slice(0, 1)")],
  ["068 detail final fallback is CV", page.includes('|| "CV"}</div>')],
  ["069 detail displays profile name", page.includes("sellerProfile?.display_name || selectedListing.seller_display_name")],
  ["070 detail keeps location privacy", page.includes("Ubicación exacta protegida")],
  ["071 detail keeps seller rating", page.includes("selectedListing.seller_rating.toFixed(1)")],
  ["072 detail keeps review count", page.includes("selectedListing.seller_review_count")],
  ["073 detail keeps seller bio conditional", page.includes("sellerProfile?.bio &&")],
  ["074 detail keeps identity verification", page.includes("sellerProfile?.identity_verified")],
  ["075 detail keeps phone verification", page.includes("sellerProfile?.phone_verified")],
  ["076 profile update synchronizer exists", page.includes("function syncSellerIdentity")],
  ["077 synchronizer requires session", page.includes("if (!session) return")],
  ["078 synchronizer limits current seller", page.includes("listing.seller_id === session.user.id")],
  ["079 synchronizer updates name", page.includes("seller_display_name: displayName")],
  ["080 synchronizer updates avatar", page.includes("seller_avatar_url: avatarUrl")],
  ["081 synchronizer keeps other sellers", page.includes(": listing;")],
  ["082 synchronizer updates public cards", page.includes("setLiveListings((current) => current.map(updateListing))")],
  ["083 synchronizer updates owner history", page.includes("setMyListings((current) => current.map(updateListing))")],
  ["084 synchronizer updates open detail", page.includes("setSelectedListing((current)")],
  ["085 profile save synchronizes name", page.includes("syncSellerIdentity(myProfile.display_name.trim(), myProfile.avatar_url)")],
  ["086 avatar upload synchronizes immediately", page.includes("syncSellerIdentity(myProfile.display_name.trim(), result.avatarUrl)")],
  ["087 avatar removal synchronizes immediately", page.includes('syncSellerIdentity(myProfile.display_name.trim(), "")')],
  ["088 upload success remains announced", page.includes("Tu foto de perfil se actualizó correctamente")],
  ["089 removal success remains announced", page.includes("Quitamos la foto de tu perfil")],
  ["090 seller row uses flex layout", css.includes(".listing-seller-line{display:flex")],
  ["091 seller row aligns avatar", css.includes("align-items:center")],
  ["092 seller row separates metadata", css.includes("border-top:1px solid var(--line)")],
  ["093 card avatar is clipped", css.includes("overflow:hidden")],
  ["094 card avatar is circular", css.includes("border-radius:50%")],
  ["095 card avatar has fixed size", css.includes("width:28px;height:28px")],
  ["096 card avatar does not shrink", css.includes("flex:0 0 auto")],
  ["097 seller images cover frames", css.includes("object-fit:cover")],
  ["098 long names are ellipsized", css.includes("text-overflow:ellipsis")],
  ["099 long names stay one line", css.includes("white-space:nowrap")],
  ["100 detail avatar clips public photo", css.includes(".seller-avatar{overflow:hidden}")],
];

assert.equal(checks.length, 100);
for (const [name, condition] of checks) test(name, () => assert.equal(condition, true));
