import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const checks = [
  ["stores safety search", page.includes('const [safetySearch, setSafetySearch]')],
  ["starts safety search empty", page.includes('setSafetySearch] = useState("")')],
  ["stores safety type", page.includes('const [safetyTypeFilter, setSafetyTypeFilter]')],
  ["supports safety case types", page.includes('"reports" | "disputes" | "actions" | "appeals"')],
  ["starts safety type at all", page.includes('setSafetyTypeFilter] = useState<"all" | "reports" | "disputes" | "actions" | "appeals">("all")')],
  ["stores safety status", page.includes('const [safetyStatusFilter, setSafetyStatusFilter]')],
  ["supports safety statuses", page.includes('"open" | "resolved" | "action"')],
  ["starts safety status at all", page.includes('setSafetyStatusFilter] = useState<"all" | "open" | "resolved" | "action">("all")')],
  ["normalizes safety search", page.includes("const safetyMatchesSearch")],
  ["defines safety status matching", page.includes("const safetyStatusMatches")],
  ["recognizes terminal states", page.includes('"resolved", "closed", "dismissed", "approved", "denied"')],
  ["supports action-needed matching", page.includes(": needsAction")],
  ["filters reports", page.includes("const filteredReports = myReports.filter")],
  ["matches report type", page.includes('safetyTypeFilter === "reports"')],
  ["searches report reason", page.includes("report.reason_code")],
  ["searches report description", page.includes('report.description || ""')],
  ["filters disputes", page.includes("const filteredDisputes = myDisputes.filter")],
  ["matches dispute type", page.includes('safetyTypeFilter === "disputes"')],
  ["searches dispute listing", page.includes('dispute.transactions?.listings?.title || ""')],
  ["searches dispute description", page.includes("dispute.description")],
  ["marks open disputes actionable", page.includes('!["resolved", "closed"].includes(dispute.status)')],
  ["filters moderation decisions", page.includes("const filteredModerationActions")],
  ["matches decision type", page.includes('safetyTypeFilter === "actions"')],
  ["searches decision type", page.includes("action.action_type")],
  ["searches decision reason", page.includes("action.reason")],
  ["decision action checks appeal", page.includes("appeal.moderation_action_id === action.id")],
  ["filters appeals", page.includes("const filteredAppeals = myAppeals.filter")],
  ["matches appeal type", page.includes('safetyTypeFilter === "appeals"')],
  ["searches appeal reason", page.includes("appeal.reason")],
  ["searches admin response", page.includes('appeal.admin_response || ""')],
  ["marks pending appeals actionable", page.includes('["submitted", "under_review"].includes(appeal.status)')],
  ["counts safety results", page.includes("const safetyResultCount")],
  ["builds safety counts", page.includes("const safetyCounts =")],
  ["counts all case types", page.includes("myReports.length + myDisputes.length + myModerationActions.length + myAppeals.length")],
  ["detects safety filters", page.includes("const safetyFiltersActive = Boolean")],
  ["provides safety reset", page.includes("function clearSafetyFilters()")],
  ["clears safety search", page.includes('setSafetySearch("")')],
  ["clears safety type", page.includes('setSafetyTypeFilter("all")')],
  ["clears safety status", page.includes('setSafetyStatusFilter("all")')],
  ["labels safety summary", page.includes('aria-label="Resumen de casos de seguridad"')],
  ["shows all cases summary", page.includes("['all','Todos']")],
  ["shows reports summary", page.includes("['reports','Reportes']")],
  ["shows disputes summary", page.includes("['disputes','Disputas']")],
  ["shows decisions summary", page.includes("['actions','Decisiones']")],
  ["shows appeals summary", page.includes("['appeals','Apelaciones']")],
  ["summary filters cases", page.includes("setSafetyTypeFilter(type)")],
  ["summary exposes pressed state", page.includes("aria-pressed={safetyTypeFilter === type}")],
  ["renders safety toolbar", page.includes('className="safety-toolbar"')],
  ["renders safety search", page.includes('value={safetySearch}')],
  ["labels safety search", page.includes('aria-label="Buscar casos de seguridad"')],
  ["renders status selector", page.includes("value={safetyStatusFilter}")],
  ["offers open status", page.includes('<option value="open">Abiertos</option>')],
  ["offers resolved status", page.includes('<option value="resolved">Finalizados</option>')],
  ["offers action status", page.includes('<option value="action">Requieren acción</option>')],
  ["announces case count", page.includes('className="safety-result-count" aria-live="polite"')],
  ["renders filtered case groups", page.includes("filteredReports.map") && page.includes("filteredDisputes.map")],
  ["shows safety empty state", page.includes("No encontramos casos con esos filtros")],
  ["offers all-cases recovery", page.includes("Ver todos los casos")],
  ["styles safety summary", css.includes(".safety-summary{display:grid")],
  ["adapts safety tools on mobile", css.includes(".safety-toolbar{grid-template-columns:1fr}")],
];

assert.equal(checks.length, 60);
for (const [name, condition] of checks) test(name, () => assert.equal(condition, true));
