import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

const checks = [
  ["stores sales search", page.includes('const [saleSearch, setSaleSearch]')],
  ["starts sales search empty", page.includes('setSaleSearch] = useState("")')],
  ["stores role filter", page.includes('const [saleRoleFilter, setSaleRoleFilter]')],
  ["supports buying filter", page.includes('"buying" | "selling"')],
  ["starts role filter at all", page.includes('setSaleRoleFilter] = useState<"all" | "buying" | "selling">("all")')],
  ["stores stage filter", page.includes('const [saleStageFilter, setSaleStageFilter]')],
  ["supports action stage", page.includes('"action" | "completed" | "disputed"')],
  ["starts stage filter at all", page.includes('setSaleStageFilter] = useState<"all" | "action" | "completed" | "disputed">("all")')],
  ["derives accepted sale offers", page.includes("const acceptedSaleOffers = myOffers.filter")],
  ["requires accepted offer", page.includes('offer.status === "accepted"')],
  ["limits sale start to seller", page.includes("offer.seller_id === session?.user.id")],
  ["avoids duplicate confirmation", page.includes("confirmation.accepted_offer_id === offer.id")],
  ["normalizes sale titles", page.includes('normalizeSearch(title || "Publicación")')],
  ["normalizes sales search", page.includes("normalizeSearch(saleSearch)")],
  ["defines role matching", page.includes("const saleRoleMatches")],
  ["matches all roles", page.includes('saleRoleFilter === "all"')],
  ["matches buyer identity", page.includes('saleRoleFilter === "buying" ? buyerId === session?.user.id')],
  ["matches seller identity", page.includes("sellerId === session?.user.id")],
  ["filters accepted sales", page.includes("const filteredAcceptedSaleOffers")],
  ["hides accepted in completed", page.includes('saleStageFilter !== "completed"')],
  ["hides accepted in disputed", page.includes('saleStageFilter !== "disputed"')],
  ["filters confirmations", page.includes("const filteredSaleConfirmations")],
  ["action shows pending confirmations", page.includes('confirmation.status === "seller_submitted"')],
  ["filters transactions", page.includes("const filteredTransactions")],
  ["action hides transactions", page.includes('saleStageFilter !== "action"')],
  ["completed matches completed", page.includes('transaction.status === "completed"')],
  ["disputed matches disputed", page.includes('transaction.status === "disputed"')],
  ["counts filtered results", page.includes("const saleResultCount")],
  ["builds stage counts", page.includes("const saleCounts =")],
  ["counts all operations", page.includes("acceptedSaleOffers.length + saleConfirmations.length + myTransactions.length")],
  ["counts action operations", page.includes("acceptedSaleOffers.length + saleConfirmations.filter")],
  ["counts completed transactions", page.includes('status === "completed").length')],
  ["counts disputed transactions", page.includes('status === "disputed").length')],
  ["detects sales filters", page.includes("const saleFiltersActive = Boolean")],
  ["provides sales reset", page.includes("function clearSaleFilters()")],
  ["clears sale search", page.includes('setSaleSearch("")')],
  ["clears sale role", page.includes('setSaleRoleFilter("all")')],
  ["clears sale stage", page.includes('setSaleStageFilter("all")')],
  ["labels sales summary", page.includes('aria-label="Resumen de compras y ventas"')],
  ["shows all stage", page.includes("['all','Todo']")],
  ["shows action stage", page.includes("['action','Requiere acción']")],
  ["shows completed stage", page.includes("['completed','Completadas']")],
  ["shows disputed stage", page.includes("['disputed','En disputa']")],
  ["stage buttons filter", page.includes("setSaleStageFilter(stage)")],
  ["stage buttons report pressed", page.includes("aria-pressed={saleStageFilter === stage}")],
  ["renders sales toolbar", page.includes('className="sale-toolbar"')],
  ["renders sales search input", page.includes('value={saleSearch}')],
  ["labels sales search", page.includes('aria-label="Buscar compras y ventas por publicación"')],
  ["renders participation selector", page.includes("value={saleRoleFilter}")],
  ["labels participation selector", page.includes('aria-label="Filtrar entre compras y ventas"')],
  ["offers purchases option", page.includes('<option value="buying">Mis compras</option>')],
  ["offers sales option", page.includes('<option value="selling">Mis ventas</option>')],
  ["announces operation count", page.includes('className="sale-result-count" aria-live="polite"')],
  ["renders filtered confirmations", page.includes("filteredSaleConfirmations.map")],
  ["renders filtered transactions", page.includes("filteredTransactions.map")],
  ["labels purchase or sale", page.includes('transaction.buyer_id === session.user.id ? "Compra" : "Venta"')],
  ["shows filtered empty state", page.includes("No encontramos operaciones con esos filtros")],
  ["offers full history reset", page.includes("Ver todo el historial")],
  ["styles sales summary", css.includes(".sale-summary-grid{display:grid")],
  ["adapts sales tools on mobile", css.includes(".sale-toolbar{grid-template-columns:1fr}")],
];

assert.equal(checks.length, 60);
for (const [name, condition] of checks) test(name, () => assert.equal(condition, true));
